# pyright: basic
from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
GENERATED = ROOT / "generated"
AUTHORITY_REVISION = "b4d28faa5fde98087f60262110a43f25f6da9eb8"
EXPECTED_SYSTEMS = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
EXPECTED_SHA256 = {
    "bazelrc.common": "e030d15a440dd58298a6189677876f91a24b3dbde9f1c2ec77d1591deb6555f7",
    "nix-bazel-policy.lock.json": "2b62ba1f6d731678b97035cc89d2f1433b9c00eaa9a3b2332ceb167bc30f2f87",
    "nix-bazel-policy.nix": "bed186e83238be6fe3e889e3725176cc7d3baa09966d076e79c990d5d719d1df",
    "toolchain-manifest.defaults.json": "95f211ac10d3b8b720299d78dee78f8e6270ccc04539177d223b833b2641c76c",
}
EXPECTED_ARTIFACT_KEYS = {
    ".github/actions/required-workflow-profile/profiles.generated.json",
    "generated/bazelrc.common",
    "generated/nix-bazel-policy.nix",
    "generated/toolchain-manifest.defaults.json",
}


def sha256_bytes(contents: bytes) -> str:
    return "sha256:" + hashlib.sha256(contents).hexdigest()


def canonical_digest(value: dict[str, Any]) -> str:
    encoded = json.dumps(value, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()
    return sha256_bytes(encoded)


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"{path} must contain an object")
    return value


def read_nix_policy() -> dict[str, Any]:
    contents = (GENERATED / "nix-bazel-policy.nix").read_text(encoding="utf-8")
    prefix = "# Generated by tools/generate_ci_policy.py. Do not edit.\nbuiltins.fromJSON ''\n"
    suffix = "\n''\n"
    if not contents.startswith(prefix) or not contents.endswith(suffix):
        raise ValueError("generated Nix policy wrapper differs from the canonical contract")
    value = json.loads(contents[len(prefix) : -len(suffix)])
    if not isinstance(value, dict):
        raise TypeError("generated Nix policy must contain an object")
    return value


class GeneratedPolicyContractTest(unittest.TestCase):
    def test_canonical_files_are_exact_immutable_copies(self) -> None:
        self.assertEqual(sorted(EXPECTED_SHA256), sorted(path.name for path in GENERATED.iterdir()))
        for name, expected in EXPECTED_SHA256.items():
            observed = hashlib.sha256((GENERATED / name).read_bytes()).hexdigest()
            self.assertEqual(expected, observed, name)

    def test_lock_binds_contract_and_local_artifacts(self) -> None:
        lock = read_json(GENERATED / "nix-bazel-policy.lock.json")
        self.assertEqual("ci.mindclade.dev/v1", lock["api_version"])
        self.assertEqual("GeneratedPolicyLock", lock["kind"])
        self.assertEqual(
            {"repository": "mindclade/.github", "revision": AUTHORITY_REVISION},
            lock["authority"],
        )
        contract = {key: value for key, value in lock.items() if key != "contract_digest"}
        self.assertEqual(canonical_digest(contract), lock["contract_digest"])
        self.assertEqual(EXPECTED_ARTIFACT_KEYS, set(lock["artifacts"]))
        for relative in (
            "generated/bazelrc.common",
            "generated/nix-bazel-policy.nix",
            "generated/toolchain-manifest.defaults.json",
        ):
            self.assertEqual(
                lock["artifacts"][relative],
                sha256_bytes((ROOT / relative).read_bytes()),
                relative,
            )

    def test_nix_bazel_projections_share_one_authority(self) -> None:
        lock = read_json(GENERATED / "nix-bazel-policy.lock.json")
        defaults = read_json(GENERATED / "toolchain-manifest.defaults.json")
        policy = read_nix_policy()
        self.assertEqual(AUTHORITY_REVISION, policy["generated"]["authority_revision"])
        self.assertEqual("mindclade/.github", policy["generated"]["authority_repository"])
        self.assertEqual(lock["authority"]["repository"], defaults["authority"]["repository"])
        self.assertEqual(lock["authority"]["revision"], defaults["authority"]["revision"])
        self.assertEqual(AUTHORITY_REVISION, defaults["authority"]["revision"])
        self.assertEqual(
            policy["generated"]["policy_digest"], defaults["authority"]["policy_digest"]
        )
        self.assertEqual(EXPECTED_SYSTEMS, policy["spec"]["systems"])
        self.assertEqual(EXPECTED_SYSTEMS, defaults["supported_systems"])
        self.assertEqual(policy["spec"]["nixpkgs"], defaults["nixpkgs"])
        self.assertEqual(policy["spec"]["bazel"]["version"], defaults["bazel"]["version"])
        rc_lines = (GENERATED / "bazelrc.common").read_text(encoding="utf-8").splitlines()
        self.assertEqual(
            policy["spec"]["bazel"]["common_rc"],
            rc_lines[1:],
        )


if __name__ == "__main__":
    unittest.main()
